import { SimulationCase } from "../constant";

interface Setting {
  simulationTimes: number;
  numberOfSet: number;
  cases: SimulationCase[];
}

export const setting: Setting = {
  simulationTimes: 1000000,
  numberOfSet: 5,
  cases: [
    "empty",
    "fill_x0",
    "fill_x1",
    "fill_x2",
    "fill_x3",
    "fill_x4",
    "fill_x5",
    "fill_x6",
    "fill_x7",
    "fill_x8",
    "fill_x0_o1",
    "fill_x0_o2",
    "fill_x0_o3",
    "fill_x0_o4",
    "fill_x0_o5",
    "fill_x0_o6",
    "fill_x0_o7",
    "fill_x0_o8",
    "fill_x1_o0",
    "fill_x1_o2",
    "fill_x1_o3",
    "fill_x1_o4",
    "fill_x1_o5",
    "fill_x1_o6",
    "fill_x1_o7",
    "fill_x1_o8",
    "fill_x2_o0",
    "fill_x2_o1",
    "fill_x2_o3",
    "fill_x2_o4",
    "fill_x2_o5",
    "fill_x2_o6",
    "fill_x2_o7",
    "fill_x2_o8",
    "fill_x3_o0",
    "fill_x3_o1",
    "fill_x3_o2",
    "fill_x3_o4",
    "fill_x3_o5",
    "fill_x3_o6",
    "fill_x3_o7",
    "fill_x3_o8",
    "fill_x4_o0",
    "fill_x4_o1",
    "fill_x4_o2",
    "fill_x4_o3",
    "fill_x4_o5",
    "fill_x4_o6",
    "fill_x4_o7",
    "fill_x4_o8",
    "fill_x5_o0",
    "fill_x5_o1",
    "fill_x5_o2",
    "fill_x5_o3",
    "fill_x5_o4",
    "fill_x5_o6",
    "fill_x5_o7",
    "fill_x5_o8",
    "fill_x6_o0",
    "fill_x6_o1",
    "fill_x6_o2",
    "fill_x6_o3",
    "fill_x6_o4",
    "fill_x6_o5",
    "fill_x6_o7",
    "fill_x6_o8",
    "fill_x7_o0",
    "fill_x7_o1",
    "fill_x7_o2",
    "fill_x7_o3",
    "fill_x7_o4",
    "fill_x7_o5",
    "fill_x7_o6",
    "fill_x7_o8",
    "fill_x8_o0",
    "fill_x8_o1",
    "fill_x8_o2",
    "fill_x8_o3",
    "fill_x8_o4",
    "fill_x8_o5",
    "fill_x8_o6",
    "fill_x8_o7",
  ],
};
